In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline
import warnings
warnings.filterwarnings('ignore')

In [2]:
train = pd.read_csv('train.csv')
test = pd.read_csv('test.csv')

In [3]:
train['dataset'] = 'train'
test['dataset'] = 'test'

In [4]:
sale_price = train[['Id','SalePrice']]

In [5]:
train.drop(['SalePrice','PoolQC','Fence','MiscFeature','Alley','MiscVal'], 1, inplace=True)
test.drop(['PoolQC','Fence','MiscFeature','Alley','MiscVal'], 1, inplace=True)

In [6]:
train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1460 entries, 0 to 1459
Data columns (total 76 columns):
Id               1460 non-null int64
MSSubClass       1460 non-null int64
MSZoning         1460 non-null object
LotFrontage      1201 non-null float64
LotArea          1460 non-null int64
Street           1460 non-null object
LotShape         1460 non-null object
LandContour      1460 non-null object
Utilities        1460 non-null object
LotConfig        1460 non-null object
LandSlope        1460 non-null object
Neighborhood     1460 non-null object
Condition1       1460 non-null object
Condition2       1460 non-null object
BldgType         1460 non-null object
HouseStyle       1460 non-null object
OverallQual      1460 non-null int64
OverallCond      1460 non-null int64
YearBuilt        1460 non-null int64
YearRemodAdd     1460 non-null int64
RoofStyle        1460 non-null object
RoofMatl         1460 non-null object
Exterior1st      1460 non-null object
Exterior2nd      1460 non-null object
MasVnrType       1452 non-null object
MasVnrArea       1452 non-null float64
ExterQual        1460 non-null object
ExterCond        1460 non-null object
Foundation       1460 non-null object
BsmtQual         1423 non-null object
BsmtCond         1423 non-null object
BsmtExposure     1422 non-null object
BsmtFinType1     1423 non-null object
BsmtFinSF1       1460 non-null int64
BsmtFinType2     1422 non-null object
BsmtFinSF2       1460 non-null int64
BsmtUnfSF        1460 non-null int64
TotalBsmtSF      1460 non-null int64
Heating          1460 non-null object
HeatingQC        1460 non-null object
CentralAir       1460 non-null object
Electrical       1459 non-null object
1stFlrSF         1460 non-null int64
2ndFlrSF         1460 non-null int64
LowQualFinSF     1460 non-null int64
GrLivArea        1460 non-null int64
BsmtFullBath     1460 non-null int64
BsmtHalfBath     1460 non-null int64
FullBath         1460 non-null int64
HalfBath         1460 non-null int64
BedroomAbvGr     1460 non-null int64
KitchenAbvGr     1460 non-null int64
KitchenQual      1460 non-null object
TotRmsAbvGrd     1460 non-null int64
Functional       1460 non-null object
Fireplaces       1460 non-null int64
FireplaceQu      770 non-null object
GarageType       1379 non-null object
GarageYrBlt      1379 non-null float64
GarageFinish     1379 non-null object
GarageCars       1460 non-null int64
GarageArea       1460 non-null int64
GarageQual       1379 non-null object
GarageCond       1379 non-null object
PavedDrive       1460 non-null object
WoodDeckSF       1460 non-null int64
OpenPorchSF      1460 non-null int64
EnclosedPorch    1460 non-null int64
3SsnPorch        1460 non-null int64
ScreenPorch      1460 non-null int64
PoolArea         1460 non-null int64
MoSold           1460 non-null int64
YrSold           1460 non-null int64
SaleType         1460 non-null object
SaleCondition    1460 non-null object
dataset          1460 non-null object
dtypes: float64(3), int64(33), object(40)
memory usage: 867.0+ KB

In [7]:
test.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1459 entries, 0 to 1458
Data columns (total 76 columns):
Id               1459 non-null int64
MSSubClass       1459 non-null int64
MSZoning         1455 non-null object
LotFrontage      1232 non-null float64
LotArea          1459 non-null int64
Street           1459 non-null object
LotShape         1459 non-null object
LandContour      1459 non-null object
Utilities        1457 non-null object
LotConfig        1459 non-null object
LandSlope        1459 non-null object
Neighborhood     1459 non-null object
Condition1       1459 non-null object
Condition2       1459 non-null object
BldgType         1459 non-null object
HouseStyle       1459 non-null object
OverallQual      1459 non-null int64
OverallCond      1459 non-null int64
YearBuilt        1459 non-null int64
YearRemodAdd     1459 non-null int64
RoofStyle        1459 non-null object
RoofMatl         1459 non-null object
Exterior1st      1458 non-null object
Exterior2nd      1458 non-null object
MasVnrType       1443 non-null object
MasVnrArea       1444 non-null float64
ExterQual        1459 non-null object
ExterCond        1459 non-null object
Foundation       1459 non-null object
BsmtQual         1415 non-null object
BsmtCond         1414 non-null object
BsmtExposure     1415 non-null object
BsmtFinType1     1417 non-null object
BsmtFinSF1       1458 non-null float64
BsmtFinType2     1417 non-null object
BsmtFinSF2       1458 non-null float64
BsmtUnfSF        1458 non-null float64
TotalBsmtSF      1458 non-null float64
Heating          1459 non-null object
HeatingQC        1459 non-null object
CentralAir       1459 non-null object
Electrical       1459 non-null object
1stFlrSF         1459 non-null int64
2ndFlrSF         1459 non-null int64
LowQualFinSF     1459 non-null int64
GrLivArea        1459 non-null int64
BsmtFullBath     1457 non-null float64
BsmtHalfBath     1457 non-null float64
FullBath         1459 non-null int64
HalfBath         1459 non-null int64
BedroomAbvGr     1459 non-null int64
KitchenAbvGr     1459 non-null int64
KitchenQual      1458 non-null object
TotRmsAbvGrd     1459 non-null int64
Functional       1457 non-null object
Fireplaces       1459 non-null int64
FireplaceQu      729 non-null object
GarageType       1383 non-null object
GarageYrBlt      1381 non-null float64
GarageFinish     1381 non-null object
GarageCars       1458 non-null float64
GarageArea       1458 non-null float64
GarageQual       1381 non-null object
GarageCond       1381 non-null object
PavedDrive       1459 non-null object
WoodDeckSF       1459 non-null int64
OpenPorchSF      1459 non-null int64
EnclosedPorch    1459 non-null int64
3SsnPorch        1459 non-null int64
ScreenPorch      1459 non-null int64
PoolArea         1459 non-null int64
MoSold           1459 non-null int64
YrSold           1459 non-null int64
SaleType         1458 non-null object
SaleCondition    1459 non-null object
dataset          1459 non-null object
dtypes: float64(11), int64(25), object(40)
memory usage: 866.4+ KB

In [8]:
combined = pd.concat([train, test]).reset_index()

In [9]:
combined.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2919 entries, 0 to 2918
Data columns (total 77 columns):
index            2919 non-null int64
Id               2919 non-null int64
MSSubClass       2919 non-null int64
MSZoning         2915 non-null object
LotFrontage      2433 non-null float64
LotArea          2919 non-null int64
Street           2919 non-null object
LotShape         2919 non-null object
LandContour      2919 non-null object
Utilities        2917 non-null object
LotConfig        2919 non-null object
LandSlope        2919 non-null object
Neighborhood     2919 non-null object
Condition1       2919 non-null object
Condition2       2919 non-null object
BldgType         2919 non-null object
HouseStyle       2919 non-null object
OverallQual      2919 non-null int64
OverallCond      2919 non-null int64
YearBuilt        2919 non-null int64
YearRemodAdd     2919 non-null int64
RoofStyle        2919 non-null object
RoofMatl         2919 non-null object
Exterior1st      2918 non-null object
Exterior2nd      2918 non-null object
MasVnrType       2895 non-null object
MasVnrArea       2896 non-null float64
ExterQual        2919 non-null object
ExterCond        2919 non-null object
Foundation       2919 non-null object
BsmtQual         2838 non-null object
BsmtCond         2837 non-null object
BsmtExposure     2837 non-null object
BsmtFinType1     2840 non-null object
BsmtFinSF1       2918 non-null float64
BsmtFinType2     2839 non-null object
BsmtFinSF2       2918 non-null float64
BsmtUnfSF        2918 non-null float64
TotalBsmtSF      2918 non-null float64
Heating          2919 non-null object
HeatingQC        2919 non-null object
CentralAir       2919 non-null object
Electrical       2918 non-null object
1stFlrSF         2919 non-null int64
2ndFlrSF         2919 non-null int64
LowQualFinSF     2919 non-null int64
GrLivArea        2919 non-null int64
BsmtFullBath     2917 non-null float64
BsmtHalfBath     2917 non-null float64
FullBath         2919 non-null int64
HalfBath         2919 non-null int64
BedroomAbvGr     2919 non-null int64
KitchenAbvGr     2919 non-null int64
KitchenQual      2918 non-null object
TotRmsAbvGrd     2919 non-null int64
Functional       2917 non-null object
Fireplaces       2919 non-null int64
FireplaceQu      1499 non-null object
GarageType       2762 non-null object
GarageYrBlt      2760 non-null float64
GarageFinish     2760 non-null object
GarageCars       2918 non-null float64
GarageArea       2918 non-null float64
GarageQual       2760 non-null object
GarageCond       2760 non-null object
PavedDrive       2919 non-null object
WoodDeckSF       2919 non-null int64
OpenPorchSF      2919 non-null int64
EnclosedPorch    2919 non-null int64
3SsnPorch        2919 non-null int64
ScreenPorch      2919 non-null int64
PoolArea         2919 non-null int64
MoSold           2919 non-null int64
YrSold           2919 non-null int64
SaleType         2918 non-null object
SaleCondition    2919 non-null object
dataset          2919 non-null object
dtypes: float64(11), int64(26), object(40)
memory usage: 1.7+ MB

In [10]:
combined.isnull().sum().sort_values(ascending=False)

FireplaceQu      1420
LotFrontage       486
GarageCond        159
GarageQual        159
GarageYrBlt       159
GarageFinish      159
GarageType        157
BsmtCond           82
BsmtExposure       82
BsmtQual           81
BsmtFinType2       80
BsmtFinType1       79
MasVnrType         24
MasVnrArea         23
MSZoning            4
BsmtHalfBath        2
Utilities           2
Functional          2
BsmtFullBath        2
BsmtFinSF2          1
BsmtUnfSF           1
BsmtFinSF1          1
Exterior2nd         1
Exterior1st         1
Electrical          1
TotalBsmtSF         1
SaleType            1
KitchenQual         1
GarageArea          1
GarageCars          1
                 ...
Condition1          0
Neighborhood        0
dataset             0
ExterQual           0
KitchenAbvGr        0
YrSold              0
MoSold              0
PoolArea            0
ScreenPorch         0
3SsnPorch           0
EnclosedPorch       0
OpenPorchSF         0
WoodDeckSF          0
PavedDrive          0
Fireplaces          0
TotRmsAbvGrd        0
BedroomAbvGr        0
ExterCond           0
HalfBath            0
FullBath            0
GrLivArea           0
LowQualFinSF        0
2ndFlrSF            0
1stFlrSF            0
CentralAir          0
HeatingQC           0
Heating             0
SaleCondition       0
Foundation          0
index               0
Length: 77, dtype: int64

In [11]:
combined[combined['FireplaceQu'].isnull()][['Fireplaces','FireplaceQu']].head(20)

    Fireplaces FireplaceQu
0            0         NaN
5            0         NaN
10           0         NaN
12           0         NaN
15           0         NaN
17           0         NaN
18           0         NaN
19           0         NaN
26           0         NaN
29           0         NaN
30           0         NaN
31           0         NaN
32           0         NaN
36           0         NaN
38           0         NaN
39           0         NaN
42           0         NaN
43           0         NaN
44           0         NaN
47           0         NaN

In [12]:
combined['FireplaceQu'] = combined['FireplaceQu'].fillna('None')

In [13]:
combined[combined['GarageType'].isnull()][['GarageType','GarageYrBlt','GarageFinish','GarageCars','GarageArea','GarageQual',
                                    'GarageCond']].head(20)

,GarageType,GarageYrBlt,GarageFinish,GarageCars,GarageArea,GarageQual,GarageCond
39,NaN,NaN,NaN,0.0,0.0,NaN,NaN
48,NaN,NaN,NaN,0.0,0.0,NaN,NaN
78,NaN,NaN,NaN,0.0,0.0,NaN,NaN
88,NaN,NaN,NaN,0.0,0.0,NaN,NaN
89,NaN,NaN,NaN,0.0,0.0,NaN,NaN
99,NaN,NaN,NaN,0.0,0.0,NaN,NaN
108,NaN,NaN,NaN,0.0,0.0,NaN,NaN
125,NaN,NaN,NaN,0.0,0.0,NaN,NaN
127,NaN,NaN,NaN,0.0,0.0,NaN,NaN
140,NaN,NaN,NaN,0.0,0.0,NaN,NaN
148,NaN,NaN,NaN,0.0,0.0,NaN,NaN
155,NaN,NaN,NaN,0.0,0.0,NaN,NaN
163,NaN,NaN,NaN,0.0,0.0,NaN,NaN
165,NaN,NaN,NaN,0.0,0.0,NaN,NaN
198,NaN,NaN,NaN,0.0,0.0,NaN,NaN
210,NaN,NaN,NaN,0.0,0.0,NaN,NaN
241,NaN,NaN,NaN,0.0,0.0,NaN,NaN
250,NaN,NaN,NaN,0.0,0.0,NaN,NaN
287,NaN,NaN,NaN,0.0,0.0,NaN,NaN
291,NaN,NaN,NaN,0.0,0.0,NaN,NaN

In [14]:
combined['GarageType'] = combined['GarageType'].fillna('None')
combined['GarageYrBlt'] = combined['GarageYrBlt'].fillna('None')
combined['GarageQual'] = combined['GarageQual'].fillna('None')
combined['GarageCond'] = combined['GarageCond'].fillna('None')
combined['GarageFinish'] = combined['GarageFinish'].fillna('None')

In [15]:
combined['LotFrontage'] = combined['LotFrontage'].fillna(train['LotFrontage'].median())

In [16]:
combined[combined['MasVnrType'].isnull()][['MasVnrType','MasVnrArea']]

     MasVnrType  MasVnrArea
234         NaN         NaN
529         NaN         NaN
650         NaN         NaN
936         NaN         NaN
973         NaN         NaN
977         NaN         NaN
1243        NaN         NaN
1278        NaN         NaN
1691        NaN         NaN
1706        NaN         NaN
1882        NaN         NaN
1992        NaN         NaN
2004        NaN         NaN
2041        NaN         NaN
2311        NaN         NaN
2325        NaN         NaN
2340        NaN         NaN
2349        NaN         NaN
2368        NaN         NaN
2592        NaN         NaN
2610        NaN       198.0
2657        NaN         NaN
2686        NaN         NaN
2862        NaN         NaN

In [17]:
combined.loc[2610,'MasVnrType'] = 'BrkFace'

In [18]:
combined[combined['MasVnrType'].isnull()][['MasVnrType','MasVnrArea']]

     MasVnrType  MasVnrArea
234         NaN         NaN
529         NaN         NaN
650         NaN         NaN
936         NaN         NaN
973         NaN         NaN
977         NaN         NaN
1243        NaN         NaN
1278        NaN         NaN
1691        NaN         NaN
1706        NaN         NaN
1882        NaN         NaN
1992        NaN         NaN
2004        NaN         NaN
2041        NaN         NaN
2311        NaN         NaN
2325        NaN         NaN
2340        NaN         NaN
2349        NaN         NaN
2368        NaN         NaN
2592        NaN         NaN
2657        NaN         NaN
2686        NaN         NaN
2862        NaN         NaN

In [19]:
combined['MasVnrType'] = combined['MasVnrType'].fillna('None')
combined['MasVnrArea'] = combined['MasVnrArea'].fillna(0)

In [20]:
combined.isnull().sum().sort_values(ascending=False)

BsmtCond         82
BsmtExposure     82
BsmtQual         81
BsmtFinType2     80
BsmtFinType1     79
MSZoning          4
Functional        2
Utilities         2
BsmtFullBath      2
BsmtHalfBath      2
BsmtFinSF1        1
BsmtFinSF2        1
BsmtUnfSF         1
Electrical        1
Exterior2nd       1
Exterior1st       1
TotalBsmtSF       1
KitchenQual       1
SaleType          1
GarageCars        1
GarageArea        1
MasVnrType        0
Id                0
MSSubClass        0
LotFrontage       0
LotArea           0
Street            0
Foundation        0
ExterCond         0
ExterQual         0
                 ..
SaleCondition     0
Heating           0
YrSold            0
MoSold            0
PoolArea          0
ScreenPorch       0
3SsnPorch         0
EnclosedPorch     0
OpenPorchSF       0
WoodDeckSF        0
PavedDrive        0
GarageCond        0
GarageQual        0
GarageFinish      0
GarageYrBlt       0
GarageType        0
FireplaceQu       0
Fireplaces        0
TotRmsAbvGrd      0
KitchenAbvGr      0
BedroomAbvGr      0
HalfBath          0
FullBath          0
GrLivArea         0
LowQualFinSF      0
2ndFlrSF          0
1stFlrSF          0
CentralAir        0
HeatingQC         0
index             0
Length: 77, dtype: int64

In [21]:
combined['TotalBsmtSF'] = combined['TotalBsmtSF'].fillna(0)
combined['BsmtUnfSF'] = combined['BsmtUnfSF'].fillna(0)
combined['BsmtFinSF1'] = combined['BsmtFinSF1'].fillna(0)
combined['BsmtFinSF2'] = combined['BsmtFinSF2'].fillna(0)

In [22]:
combined.isnull().sum().sort_values(ascending=False)

BsmtExposure     82
BsmtCond         82
BsmtQual         81
BsmtFinType2     80
BsmtFinType1     79
MSZoning          4
Utilities         2
BsmtFullBath      2
BsmtHalfBath      2
Functional        2
Electrical        1
SaleType          1
GarageArea        1
GarageCars        1
Exterior1st       1
Exterior2nd       1
KitchenQual       1
LandContour       0
RoofMatl          0
MasVnrType        0
ExterQual         0
MasVnrArea        0
LotArea           0
ExterCond         0
Foundation        0
MSSubClass        0
Id                0
LotFrontage       0
YearRemodAdd      0
RoofStyle         0
                 ..
MoSold            0
PoolArea          0
ScreenPorch       0
3SsnPorch         0
EnclosedPorch     0
OpenPorchSF       0
WoodDeckSF        0
PavedDrive        0
GarageCond        0
GarageQual        0
GarageFinish      0
GarageYrBlt       0
GarageType        0
Fireplaces        0
BsmtFinSF2        0
TotRmsAbvGrd      0
KitchenAbvGr      0
BedroomAbvGr      0
HalfBath          0
FullBath          0
GrLivArea         0
LowQualFinSF      0
2ndFlrSF          0
1stFlrSF          0
CentralAir        0
HeatingQC         0
Heating           0
SaleCondition     0
BsmtUnfSF         0
index             0
Length: 77, dtype: int64

In [23]:
combined['Functional'] = combined['Functional'].fillna('Typ')

In [24]:
combined['BsmtFullBath'] = combined['BsmtFullBath'].fillna(0)
combined['BsmtHalfBath'] = combined['BsmtHalfBath'].fillna(0)

In [25]:
train['GarageCars'].median()

2.0

In [26]:
train['GarageArea'].median()

480.0

In [27]:
combined['GarageCars'] = combined['GarageCars'].fillna(2.0)
combined['GarageArea'] = combined['GarageArea'].fillna(480.0)

In [28]:
combined['Exterior1st'] = combined['Exterior1st'].fillna('Wd Sdng')
combined['Exterior2nd'] = combined['Exterior2nd'].fillna('Wd Sdng')

In [29]:
combined['KitchenQual'] = combined['KitchenQual'].fillna('TA')

In [30]:
combined['SaleType'] = combined['SaleType'].fillna('WD')

In [31]:
combined['Utilities'] = combined['Utilities'].fillna('AllPub')

In [32]:
combined[combined['MSZoning'].isnull()]

,index,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,LotShape,LandContour,Utilities,...,OpenPorchSF,EnclosedPorch,3SsnPorch,ScreenPorch,PoolArea,MoSold,YrSold,SaleType,SaleCondition,dataset
1915,455,1916,30,NaN,109.0,21780,Grvl,Reg,Lvl,AllPub,...,24,0,0,0,0,3,2009,ConLD,Normal,test
2216,756,2217,20,NaN,80.0,14584,Pave,Reg,Low,AllPub,...,0,0,0,0,0,2,2008,WD,Abnorml,test
2250,790,2251,70,NaN,69.0,56600,Pave,IR1,Low,AllPub,...,0,0,0,0,0,1,2008,WD,Normal,test
2904,1444,2905,20,NaN,125.0,31250,Pave,Reg,Lvl,AllPub,...,0,135,0,0,0,5,2006,WD,Normal,test

In [33]:
combined[combined['Neighborhood'] == 'IDOTRR']['MSZoning'].value_counts()

RM         68
C (all)    22
Name: MSZoning, dtype: int64

In [34]:
combined.loc[1915,'MSZoning'] = 'RM'
combined.loc[2216,'MSZoning'] = 'RM'
combined.loc[2250,'MSZoning'] = 'RM'
combined.loc[2904,'MSZoning'] = 'RL'

In [35]:
combined.isnull().sum().sort_values(ascending=False)

BsmtExposure     82
BsmtCond         82
BsmtQual         81
BsmtFinType2     80
BsmtFinType1     79
Electrical        1
dataset           0
MasVnrType        0
RoofStyle         0
RoofMatl          0
Exterior1st       0
Exterior2nd       0
Foundation        0
MasVnrArea        0
ExterQual         0
ExterCond         0
YearBuilt         0
BsmtFinSF1        0
YearRemodAdd      0
OverallCond       0
BsmtUnfSF         0
LandContour       0
Id                0
MSSubClass        0
MSZoning          0
LotFrontage       0
LotArea           0
Street            0
LotShape          0
Utilities         0
                 ..
PavedDrive        0
WoodDeckSF        0
OpenPorchSF       0
EnclosedPorch     0
3SsnPorch         0
ScreenPorch       0
PoolArea          0
MoSold            0
YrSold            0
SaleType          0
GarageYrBlt       0
FireplaceQu       0
Heating           0
Fireplaces        0
HeatingQC         0
CentralAir        0
1stFlrSF          0
2ndFlrSF          0
LowQualFinSF      0
GrLivArea         0
BsmtFullBath      0
BsmtHalfBath      0
FullBath          0
HalfBath          0
BedroomAbvGr      0
KitchenAbvGr      0
KitchenQual       0
TotRmsAbvGrd      0
Functional        0
index             0
Length: 77, dtype: int64

In [36]:
combined['Electrical'] = combined['Electrical'].fillna('SBrkr')

In [37]:
combined.isnull().sum().sort_values(ascending=False)

BsmtExposure     82
BsmtCond         82
BsmtQual         81
BsmtFinType2     80
BsmtFinType1     79
dataset           0
MasVnrType        0
YearRemodAdd      0
RoofStyle         0
RoofMatl          0
Exterior1st       0
Exterior2nd       0
ExterCond         0
MasVnrArea        0
ExterQual         0
BsmtUnfSF         0
Foundation        0
BsmtFinSF1        0
YearBuilt         0
OverallCond       0
OverallQual       0
HouseStyle        0
Id                0
MSSubClass        0
MSZoning          0
LotFrontage       0
LotArea           0
Street            0
LotShape          0
LandContour       0
                 ..
PavedDrive        0
OpenPorchSF       0
Heating           0
EnclosedPorch     0
3SsnPorch         0
ScreenPorch       0
PoolArea          0
MoSold            0
YrSold            0
SaleType          0
GarageType        0
FireplaceQu       0
Fireplaces        0
Functional        0
HeatingQC         0
CentralAir        0
Electrical        0
1stFlrSF          0
2ndFlrSF          0
LowQualFinSF      0
GrLivArea         0
BsmtFullBath      0
BsmtHalfBath      0
FullBath          0
HalfBath          0
BedroomAbvGr      0
KitchenAbvGr      0
KitchenQual       0
TotRmsAbvGrd      0
index             0
Length: 77, dtype: int64

In [38]:
combined[combined['BsmtQual'].isnull()][['BsmtQual','BsmtCond','BsmtFinType1','BsmtFinType2','BsmtExposure','TotalBsmtSF']]

     BsmtQual BsmtCond BsmtFinType1 BsmtFinType2 BsmtExposure  TotalBsmtSF
17        NaN      NaN          NaN          NaN          NaN          0.0
39        NaN      NaN          NaN          NaN          NaN          0.0
90        NaN      NaN          NaN          NaN          NaN          0.0
102       NaN      NaN          NaN          NaN          NaN          0.0
156       NaN      NaN          NaN          NaN          NaN          0.0
182       NaN      NaN          NaN          NaN          NaN          0.0
259       NaN      NaN          NaN          NaN          NaN          0.0
342       NaN      NaN          NaN          NaN          NaN          0.0
362       NaN      NaN          NaN          NaN          NaN          0.0
371       NaN      NaN          NaN          NaN          NaN          0.0
392       NaN      NaN          NaN          NaN          NaN          0.0
520       NaN      NaN          NaN          NaN          NaN          0.0
532       NaN      NaN          NaN          NaN          NaN          0.0
533       NaN      NaN          NaN          NaN          NaN          0.0
553       NaN      NaN          NaN          NaN          NaN          0.0
646       NaN      NaN          NaN          NaN          NaN          0.0
705       NaN      NaN          NaN          NaN          NaN          0.0
736       NaN      NaN          NaN          NaN          NaN          0.0
749       NaN      NaN          NaN          NaN          NaN          0.0
778       NaN      NaN          NaN          NaN          NaN          0.0
868       NaN      NaN          NaN          NaN          NaN          0.0
894       NaN      NaN          NaN          NaN          NaN          0.0
897       NaN      NaN          NaN          NaN          NaN          0.0
984       NaN      NaN          NaN          NaN          NaN          0.0
1000      NaN      NaN          NaN          NaN          NaN          0.0
1011      NaN      NaN          NaN          NaN          NaN          0.0
1035      NaN      NaN          NaN          NaN          NaN          0.0
1045      NaN      NaN          NaN          NaN          NaN          0.0
1048      NaN      NaN          NaN          NaN          NaN          0.0
1049      NaN      NaN          NaN          NaN          NaN          0.0
...       ...      ...          ...          ...          ...          ...
2068      NaN      NaN          NaN          NaN          NaN          0.0
2120      NaN      NaN          NaN          NaN          NaN          0.0
2122      NaN      NaN          NaN          NaN          NaN          0.0
2188      NaN      NaN          NaN          NaN          NaN          0.0
2189      NaN      NaN          NaN          NaN          NaN          0.0
2190      NaN      NaN          NaN          NaN          NaN          0.0
2193      NaN      NaN          NaN          NaN          NaN          0.0
2216      NaN      NaN          NaN          NaN          NaN          0.0
2217      NaN       Fa          Unf          Unf           No        173.0
2218      NaN       TA          Unf          Unf           No        356.0
2224      NaN      NaN          NaN          NaN          NaN          0.0
2387      NaN      NaN          NaN          NaN          NaN          0.0
2435      NaN      NaN          NaN          NaN          NaN          0.0
2452      NaN      NaN          NaN          NaN          NaN          0.0
2453      NaN      NaN          NaN          NaN          NaN          0.0
2490      NaN      NaN          NaN          NaN          NaN          0.0
2498      NaN      NaN          NaN          NaN          NaN          0.0
2547      NaN      NaN          NaN          NaN          NaN          0.0
2552      NaN      NaN          NaN          NaN          NaN          0.0
2564      NaN      NaN          NaN          NaN          NaN          0.0
2578      NaN      NaN          NaN          NaN          NaN          0.0
2599      NaN      NaN          NaN          NaN          NaN          0.0
2702      NaN      NaN          NaN          NaN          NaN          0.0
2763      NaN      NaN          NaN          NaN          NaN          0.0
2766      NaN      NaN          NaN          NaN          NaN          0.0
2803      NaN      NaN          NaN          NaN          NaN          0.0
2804      NaN      NaN          NaN          NaN          NaN          0.0
2824      NaN      NaN          NaN          NaN          NaN          0.0
2891      NaN      NaN          NaN          NaN          NaN          0.0
2904      NaN      NaN          NaN          NaN          NaN          0.0

[81 rows x 6 columns]

In [39]:
combined[combined['BsmtQual'] == 'Fa']['BsmtCond'].value_counts()

TA    61
Fa    22
Po     3
Gd     2
Name: BsmtCond, dtype: int64

In [40]:
combined[combined['BsmtQual'] == 'TA']['BsmtCond'].value_counts()

TA    1177
Fa      72
Gd      31
Po       1
Name: BsmtCond, dtype: int64

In [41]:
combined.loc[2217,'BsmtQual'] = 'Fa'
combined.loc[2218,'BsmtQual'] = 'TA'

In [42]:
combined[combined['BsmtExposure'].isnull()][['BsmtQual','BsmtCond','BsmtFinType1','BsmtFinType2','BsmtExposure','TotalBsmtSF']]

     BsmtQual BsmtCond BsmtFinType1 BsmtFinType2 BsmtExposure  TotalBsmtSF
17        NaN      NaN          NaN          NaN          NaN          0.0
39        NaN      NaN          NaN          NaN          NaN          0.0
90        NaN      NaN          NaN          NaN          NaN          0.0
102       NaN      NaN          NaN          NaN          NaN          0.0
156       NaN      NaN          NaN          NaN          NaN          0.0
182       NaN      NaN          NaN          NaN          NaN          0.0
259       NaN      NaN          NaN          NaN          NaN          0.0
342       NaN      NaN          NaN          NaN          NaN          0.0
362       NaN      NaN          NaN          NaN          NaN          0.0
371       NaN      NaN          NaN          NaN          NaN          0.0
392       NaN      NaN          NaN          NaN          NaN          0.0
520       NaN      NaN          NaN          NaN          NaN          0.0
532       NaN      NaN          NaN          NaN          NaN          0.0
533       NaN      NaN          NaN          NaN          NaN          0.0
553       NaN      NaN          NaN          NaN          NaN          0.0
646       NaN      NaN          NaN          NaN          NaN          0.0
705       NaN      NaN          NaN          NaN          NaN          0.0
736       NaN      NaN          NaN          NaN          NaN          0.0
749       NaN      NaN          NaN          NaN          NaN          0.0
778       NaN      NaN          NaN          NaN          NaN          0.0
868       NaN      NaN          NaN          NaN          NaN          0.0
894       NaN      NaN          NaN          NaN          NaN          0.0
897       NaN      NaN          NaN          NaN          NaN          0.0
948        Gd       TA          Unf          Unf          NaN        936.0
984       NaN      NaN          NaN          NaN          NaN          0.0
1000      NaN      NaN          NaN          NaN          NaN          0.0
1011      NaN      NaN          NaN          NaN          NaN          0.0
1035      NaN      NaN          NaN          NaN          NaN          0.0
1045      NaN      NaN          NaN          NaN          NaN          0.0
1048      NaN      NaN          NaN          NaN          NaN          0.0
...       ...      ...          ...          ...          ...          ...
2066      NaN      NaN          NaN          NaN          NaN          0.0
2068      NaN      NaN          NaN          NaN          NaN          0.0
2120      NaN      NaN          NaN          NaN          NaN          0.0
2122      NaN      NaN          NaN          NaN          NaN          0.0
2188      NaN      NaN          NaN          NaN          NaN          0.0
2189      NaN      NaN          NaN          NaN          NaN          0.0
2190      NaN      NaN          NaN          NaN          NaN          0.0
2193      NaN      NaN          NaN          NaN          NaN          0.0
2216      NaN      NaN          NaN          NaN          NaN          0.0
2224      NaN      NaN          NaN          NaN          NaN          0.0
2348       Gd       TA          Unf          Unf          NaN        725.0
2387      NaN      NaN          NaN          NaN          NaN          0.0
2435      NaN      NaN          NaN          NaN          NaN          0.0
2452      NaN      NaN          NaN          NaN          NaN          0.0
2453      NaN      NaN          NaN          NaN          NaN          0.0
2490      NaN      NaN          NaN          NaN          NaN          0.0
2498      NaN      NaN          NaN          NaN          NaN          0.0
2547      NaN      NaN          NaN          NaN          NaN          0.0
2552      NaN      NaN          NaN          NaN          NaN          0.0
2564      NaN      NaN          NaN          NaN          NaN          0.0
2578      NaN      NaN          NaN          NaN          NaN          0.0
2599      NaN      NaN          NaN          NaN          NaN          0.0
2702      NaN      NaN          NaN          NaN          NaN          0.0
2763      NaN      NaN          NaN          NaN          NaN          0.0
2766      NaN      NaN          NaN          NaN          NaN          0.0
2803      NaN      NaN          NaN          NaN          NaN          0.0
2804      NaN      NaN          NaN          NaN          NaN          0.0
2824      NaN      NaN          NaN          NaN          NaN          0.0
2891      NaN      NaN          NaN          NaN          NaN          0.0
2904      NaN      NaN          NaN          NaN          NaN          0.0

[82 rows x 6 columns]

In [43]:
combined.isnull().sum().sort_values(ascending=False)

BsmtExposure     82
BsmtCond         82
BsmtFinType2     80
BsmtFinType1     79
BsmtQual         79
dataset           0
MasVnrType        0
YearRemodAdd      0
RoofStyle         0
RoofMatl          0
Exterior1st       0
Exterior2nd       0
ExterCond         0
MasVnrArea        0
ExterQual         0
BsmtUnfSF         0
Foundation        0
BsmtFinSF1        0
YearBuilt         0
OverallCond       0
OverallQual       0
HouseStyle        0
Id                0
MSSubClass        0
MSZoning          0
LotFrontage       0
LotArea           0
Street            0
LotShape          0
LandContour       0
                 ..
PavedDrive        0
OpenPorchSF       0
Heating           0
EnclosedPorch     0
3SsnPorch         0
ScreenPorch       0
PoolArea          0
MoSold            0
YrSold            0
SaleType          0
GarageType        0
FireplaceQu       0
Fireplaces        0
Functional        0
HeatingQC         0
CentralAir        0
Electrical        0
1stFlrSF          0
2ndFlrSF          0
LowQualFinSF      0
GrLivArea         0
BsmtFullBath      0
BsmtHalfBath      0
FullBath          0
HalfBath          0
BedroomAbvGr      0
KitchenAbvGr      0
KitchenQual       0
TotRmsAbvGrd      0
index             0
Length: 77, dtype: int64

In [44]:
combined['BsmtQual'] = combined['BsmtQual'].fillna('None')
combined['BsmtCond'] = combined['BsmtCond'].fillna('None')
combined['BsmtFinType1'] = combined['BsmtFinType1'].fillna('None')
combined['BsmtFinType2'] = combined['BsmtFinType2'].fillna('None')
combined['BsmtExposure'] = combined['BsmtExposure'].fillna('None')

In [45]:
combined.isnull().sum().sort_values(ascending=False)

dataset          0
ExterQual        0
YearRemodAdd     0
RoofStyle        0
RoofMatl         0
Exterior1st      0
Exterior2nd      0
MasVnrType       0
MasVnrArea       0
ExterCond        0
BsmtUnfSF        0
Foundation       0
BsmtQual         0
BsmtCond         0
BsmtExposure     0
BsmtFinType1     0
BsmtFinSF1       0
BsmtFinType2     0
YearBuilt        0
OverallCond      0
OverallQual      0
HouseStyle       0
Id               0
MSSubClass       0
MSZoning         0
LotFrontage      0
LotArea          0
Street           0
LotShape         0
LandContour      0
                ..
PavedDrive       0
OpenPorchSF      0
Heating          0
EnclosedPorch    0
3SsnPorch        0
ScreenPorch      0
PoolArea         0
MoSold           0
YrSold           0
SaleType         0
GarageType       0
FireplaceQu      0
Fireplaces       0
Functional       0
HeatingQC        0
CentralAir       0
Electrical       0
1stFlrSF         0
2ndFlrSF         0
LowQualFinSF     0
GrLivArea        0
BsmtFullBath     0
BsmtHalfBath     0
FullBath         0
HalfBath         0
BedroomAbvGr     0
KitchenAbvGr     0
KitchenQual      0
TotRmsAbvGrd     0
index            0
Length: 77, dtype: int64

In [46]:
combined['MSSubClass'] = combined['MSSubClass'].astype('category')
combined['OverallQual'] = combined['OverallQual'].astype('category')
combined['OverallCond'] = combined['OverallCond'].astype('category')
combined['YearBuilt'] = combined['YearBuilt'].astype('category')
combined['YearRemodAdd'] = combined['YearRemodAdd'].astype('category')
combined['GarageYrBlt'] = combined['GarageYrBlt'].astype('category')
combined['MoSold'] = combined['MoSold'].astype('category')
combined['YrSold'] = combined['YrSold'].astype('category')
combined['GarageCars'] = combined['GarageCars'].astype('category')
combined['Fireplaces'] = combined['Fireplaces'].astype('category')
combined['TotRmsAbvGrd'] = combined['TotRmsAbvGrd'].astype('category')
combined['KitchenAbvGr'] = combined['KitchenAbvGr'].astype('category')
combined['BedroomAbvGr'] = combined['BedroomAbvGr'].astype('category')
combined['HalfBath'] = combined['HalfBath'].astype('category')
combined['FullBath'] = combined['FullBath'].astype('category')
combined['BsmtHalfBath'] = combined['BsmtHalfBath'].astype('category')
combined['BsmtFullBath'] = combined['BsmtFullBath'].astype('category')
combined['BedroomAbvGr'] = combined['BedroomAbvGr'].astype('category')

In [47]:
objects = combined.select_dtypes(include='object')
cols = objects.columns
for i in cols:
    combined[i] = combined[i].astype('category')

In [48]:
combined.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2919 entries, 0 to 2918
Data columns (total 77 columns):
index            2919 non-null int64
Id               2919 non-null int64
MSSubClass       2919 non-null category
MSZoning         2919 non-null category
LotFrontage      2919 non-null float64
LotArea          2919 non-null int64
Street           2919 non-null category
LotShape         2919 non-null category
LandContour      2919 non-null category
Utilities        2919 non-null category
LotConfig        2919 non-null category
LandSlope        2919 non-null category
Neighborhood     2919 non-null category
Condition1       2919 non-null category
Condition2       2919 non-null category
BldgType         2919 non-null category
HouseStyle       2919 non-null category
OverallQual      2919 non-null category
OverallCond      2919 non-null category
YearBuilt        2919 non-null category
YearRemodAdd     2919 non-null category
RoofStyle        2919 non-null category
RoofMatl         2919 non-null category
Exterior1st      2919 non-null category
Exterior2nd      2919 non-null category
MasVnrType       2919 non-null category
MasVnrArea       2919 non-null float64
ExterQual        2919 non-null category
ExterCond        2919 non-null category
Foundation       2919 non-null category
BsmtQual         2919 non-null category
BsmtCond         2919 non-null category
BsmtExposure     2919 non-null category
BsmtFinType1     2919 non-null category
BsmtFinSF1       2919 non-null float64
BsmtFinType2     2919 non-null category
BsmtFinSF2       2919 non-null float64
BsmtUnfSF        2919 non-null float64
TotalBsmtSF      2919 non-null float64
Heating          2919 non-null category
HeatingQC        2919 non-null category
CentralAir       2919 non-null category
Electrical       2919 non-null category
1stFlrSF         2919 non-null int64
2ndFlrSF         2919 non-null int64
LowQualFinSF     2919 non-null int64
GrLivArea        2919 non-null int64
BsmtFullBath     2919 non-null category
BsmtHalfBath     2919 non-null category
FullBath         2919 non-null category
HalfBath         2919 non-null category
BedroomAbvGr     2919 non-null category
KitchenAbvGr     2919 non-null category
KitchenQual      2919 non-null category
TotRmsAbvGrd     2919 non-null category
Functional       2919 non-null category
Fireplaces       2919 non-null category
FireplaceQu      2919 non-null category
GarageType       2919 non-null category
GarageYrBlt      2919 non-null category
GarageFinish     2919 non-null category
GarageCars       2919 non-null category
GarageArea       2919 non-null float64
GarageQual       2919 non-null category
GarageCond       2919 non-null category
PavedDrive       2919 non-null category
WoodDeckSF       2919 non-null int64
OpenPorchSF      2919 non-null int64
EnclosedPorch    2919 non-null int64
3SsnPorch        2919 non-null int64
ScreenPorch      2919 non-null int64
PoolArea         2919 non-null int64
MoSold           2919 non-null category
YrSold           2919 non-null category
SaleType         2919 non-null category
SaleCondition    2919 non-null category
dataset          2919 non-null category
dtypes: category(57), float64(7), int64(13)
memory usage: 648.3 KB

In [49]:
combined['bathrooms'] = (combined['HalfBath'].astype('int') * 0.5 + combined['FullBath'].astype('int') \
                    + combined['BsmtFullBath'].astype('int') + combined['BsmtHalfBath'].astype('int') * 0.5 \
                     ).astype('category')

combined['total_sq_ft'] = combined['BsmtFinSF1'] + combined['BsmtFinSF2'] + combined['1stFlrSF'] + combined['2ndFlrSF']

combined['total_sq_ft_plus_unf'] = combined['BsmtFinSF1'] + combined['BsmtFinSF2'] + combined['1stFlrSF'] + combined['2ndFlrSF'] \
                                + combined['BsmtUnfSF']
    
def remod(row):
    remod = 0
    if row['YearRemodAdd'] > row['YearBuilt']:
        remod = 1
    return remod

combined['remodel'] = combined.apply(remod, axis=1)

combined['total_porch_sf'] = combined['WoodDeckSF'] + combined['OpenPorchSF'] + combined['EnclosedPorch'] + combined['3SsnPorch'] + \
                          combined['ScreenPorch']

In [50]:
combined.to_csv('combined.csv', index=False)

In [51]:
test = combined[combined['dataset'] == 'test'].to_csv('modeling_test.csv', index=False)
train = combined[combined['dataset'] == 'train'].to_csv('modeling_train.csv', index=False)